name: Generate Datas

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: actions/checkout@v2

      - name: Generate Snake Game Animation
        uses: Platane/snk@master
        with:
          github_user_name: mariandr4de 
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy Snake Game Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
